clusterArchitecture: single                     # <string:  cluster architecture, valid values ["single" | "ha" | "eha"]>
provider: bah:aws                               # <string:  cloud provider id>
clusterName: tons-biganimal-cluster           # <string:  cluster name>
password: enterprisedb                # <string:  cluster password (must be at least 12 characters)>
iamAuthentication: false                    # <bool:    Identity and Access Management, enabling IAM authentication will allow database users to authenticate to Postgres using your cloud provider's IAM(currently supported only for AWS). You can set up IAM authentication after your cluster is provisioned.>
postgresType: epas                          # <string:  postgresType id, valid values ["postgres" | "epas" | "pgextended"]>
postgresVersion: "15"                       # <string:  postgres version>
region: eu-west-1                           # <string:  provider region id>
instanceType: aws:m5.large                     # <string:  instance type id>
volumeType: gp3             # <string:  volume type id>
volumePropertySize: "4Gi"                   # <string:  Applicable to AWS gp3 only and Azure Ultradisk, volume size in Byte, you may append unit suffix 'Gi' or 'G'.>
volumePropertyIOPS: 3000                    # <number>: Applicable to AWS gp3 and Azure Ultradisk, volume Input/Output Operations Per Second> 
networking: public                          # <string:  input "private" or "public" network>
pgConfigMap:                                # <Object:  Postgres configuration>
  application_name: test_app
  array_nulls: true
backupRetentionPeriod: 30d
readOnlyWorkloads: false
