# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'getoptlong'

opts = GetoptLong.new(
    [ '--key', GetoptLong::REQUIRED_ARGUMENT ],
    [ '--user', GetoptLong::REQUIRED_ARGUMENT ]
)

username=''
passkey=''

opts.each do |opt, arg|
  case opt
    when '--user'
      username=arg
    when '--key'
      passkey=arg
  end
end


Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  config.vm.box = "centos/8"
  config.vm.network "private_network", ip: "10.10.10.10"
  config.vm.network "public_network"
  config.vm.provider "virtualbox" do |vb|
    vb.name = "edbdemo"
    vb.memory = "8196"
    vb.cpus = "4"
  end
  config.vm.provision :shell, :path => "bootstrap.sh",
      :args => [username, passkey]
end
