#!/bin/sh

CONTAINER_EDB="edbdemo"
CONTAINER_ORA="orademo"
PW=$(docker logs $CONTAINER_ORA 2> /dev/null | grep "ORACLE PASSWORD FOR SYS AND SYSTEM" | cut -d : -f 2 | xargs)
IP=$(docker inspect $CONTAINER_ORA 2> /dev/null | grep "\<IPAddress\>" | head -n 1 | cut -d ":" -f 2 | tr -d ' ",')

MYUID=$(id -u "$USER")
MYGID=$(id -g "$USER")

CMD="sqlplus sys/${PW}@//${IP}:1521/XEPDB1 as sysdba @edb_ddl_extractor.sql"
docker exec -it -u "${MYUID}:${MYGID}" -w /mnt $CONTAINER_EDB "$CMD"

echo
echo "This was the command executed by this script: $CMD"
