#!/bin/sh
source env.sh

IPEDB=$(docker inspect $CONTAINER_EDB 2> /dev/null | grep "\<IPAddress\>" | head -n 1 | cut -d ":" -f 2 | tr -d ' ",')
IPORA=$(docker inspect $CONTAINER_ORA 2> /dev/null | grep "\<IPAddress\>" | head -n 1 | cut -d ":" -f 2 | tr -d ' ",')
PW=$(docker logs $CONTAINER_ORA 2> /dev/null | grep "ORACLE PASSWORD FOR SYS AND SYSTEM" | cut -d : -f 2 | xargs)

echo "EDB IP Address: $IPEDB"
echo "Oracle Database IP Address: $IPORA"
echo "Oracle Database Password: $PW"
printf "${N}Access PL/SQL using ${H}docker/connect${N}\n"
biganimal cluster show
biganimal cluster show-connection --provider bah:aws --region eu-west-1 --name tons-biganimal-cluster
