#!/bin/sh

CONTAINER="orademo"
MSG="DATABASE IS READY TO USE!"

while true; do
	docker logs $CONTAINER | grep -m 1 -q "$MSG"
	RC=$?
	if [ $RC -ne 0 ]; then
		STATUS=$(docker logs $CONTAINER | tail -n 1)
		echo "Waiting for Oracle database to become available. This can take a while... $STATUS"
		sleep 5
	else
		break
	fi
done

PW=$(docker logs $CONTAINER | grep "ORACLE PASSWORD FOR SYS AND SYSTEM" | cut -d : -f 2 | xargs)

CMD1="sqlplus system/${PW}@XEPDB1 @mksample $PW $PW hrpluspw oepw pmpw ixpw shpw bipw users temp /tmp/orademo/ localhost:1521/XEPDB1"
CMD2="sqlplus system/${PW}@XEPDB1 @co_main $PW localhost:1521/XEPDB1 users temp"
docker exec -w /usr/local/db-sample-schemas $CONTAINER $CMD1
docker exec -w /usr/local/db-sample-schemas/customer_orders $CONTAINER $CMD2

echo
echo "These were the commands executed by this script:"
echo "  $CMD1"
echo "  $CMD2"
