#!/bin/sh

CONTAINER="orademo"
PW=`docker logs $CONTAINER | grep "ORACLE PASSWORD FOR SYS AND SYSTEM" | cut -d : -f 2 | xargs`
docker exec -w /usr/local/db-sample-schemas $CONTAINER sqlplus \
		system/${PW}@XEPDB1 @mksample $PW $PW hrpw oepw pmpw ixpw shpw bipw \
		users temp /tmp/orademo/ localhost:1521/XEPDB1
docker exec -w /usr/local/db-sample-schemas/customer_orders \
		$CONTAINER sqlplus system/${PW}@XEPDB1 @co_main $PW \
		localhost:1521/XEPDB1 users temp
